# Generated by Django 5.0.6 on 2024-05-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
